server:
  context-path: /cmfz
  port: 8990
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/cmfz
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
    date-format: yyyy-MM-dd HH:mm:ss
  http:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 10000Mb
    encoding: utf-8
mybatis:
  mapper-locations: com/baizhi/cmfz/dao/*Mapper.xml
  type-aliases-package: com.baizhi.cmfz.entity